language: cpp
dist: bionic
os:
  - linux
addons:
  apt:
    update: true
compiler:
  - gcc
before_install:
  - sudo apt-get install -y libboost-dev lcov
script:
  - mkdir release
  - cd release
  - cmake -DCMAKE_BUILD_TYPE=Debug -DCODE_COVERAGE=True ..
  - cmake  --build .
  - ctest .
after_success:
  # Create lcov report
  - lcov --capture --directory . --output-file coverage.info --exclude 
  - lcov --remove coverage.info '/usr/*' --output-file coverage.info # filter system-files
  - lcov --remove coverage.info 'tests/*' --output-file coverage.info # filter test files
  - lcov --remove coverage.info 'external/*' --output-file coverage.info # filter external files
  - lcov --list coverage.info # debug info
  # Uploading report to CodeCov
  - bash <(curl -s https://codecov.io/bash) -f coverage.info || echo "Codecov did not collect coverage reports"