version: '3'
services:
    # arb-ethbridge deploys on ganache-cli
    arb-ethbridge:
        image: arb-ethbridge
        build: arb-ethbridge
        ports:
            - "7545:7545"

    arb-validator-coordinator:
        image: arb-validator
        build: arb-validator
        command: >
            sh -c "sleep 15 &&
                   go run ./cmd/coordinatorServer/main.go addresses.json contract.ao ws://arb-ethbridge:7545"
        ports:
            - "1235:1235"

    arb-validator1:
        image: arb-validator
        command: >
            sh -c "sleep 25 &&
                   go run ./cmd/server/main.go addresses.json contract.ao wss://arb-validator-coordinator:1236/ws ws://arb-ethbridge:7545 1"

    arb-validator2:
        image: arb-validator
        command: >
            sh -c "sleep 25 &&
                   go run ./cmd/server/main.go addresses.json contract.ao wss://arb-validator-coordinator:1236/ws ws://arb-ethbridge:7545 2"
    # demo-app deploys with compiled.json
    # Depends on arb-web3-provider in same directory
    demo-app:
        image: demo-app
        build: demo-app
        ports:
            - "8080:8080"
