version: '3'
services:
    compiler:
        build: arbc-solidity
    eth-bridge:
        build: arbitrum-verifier-solidity
        ports:
            - "7545:7545"
    validator:
        build: arbitrum-go
        ports:
            - "1235:1235"
        network_mode: "host"
        depends_on:
            - compiler
            - eth-bridge
        environment:
            - DELAY=15
    demo:
        build: demo-app
        ports:
            - "8080:8080"
