version: '3'
services:
    arb-ethbridge:
        image: arb-ethbridge
        build:
#           context: https://github.com/OffchainLabs/arb-ethbridge.git#alpha
            context: ./arb-ethbridge
            args:
                MNEMONIC: "jar deny prosper gasp flush glass core corn alarm treat leg smart"
                NUM_WALLETS: 3
                PORT: 7545
        ports:
            - "7545:7545"

    arb-validator-coordinator:
        build:
#           context: https://github.com/OffchainLabs/arb-validator.git#alpha
            context: ./arb-validator
            args:
                WAIT_FOR: "arb-ethbridge:7545"
                ETH_URL: "ws://arb-ethbridge:7545"
                ID: 0
        ports:
            - "1235:1235"
            - "1236:1236"
        depends_on:
            - arb-ethbridge

    arb-validator1:
        build:
#           context: https://github.com/OffchainLabs/arb-validator.git#alpha
            context: ./arb-validator
            args:
                WAIT_FOR: "arb-validator-coordinator:1236"
                ETH_URL: "ws://arb-ethbridge:7545"
                COORDINATOR_URL: "wss://arb-validator-coordinator:1236/ws"
                ID: 1

    arb-validator2:
        build:
#           context: https://github.com/OffchainLabs/arb-validator.git#alpha
            context: ./arb-validator
            args:
                WAIT_FOR: "arb-validator-coordinator:1236"
                ETH_URL: "ws://arb-ethbridge:7545"
                COORDINATOR_URL: "wss://arb-validator-coordinator:1236/ws"
                ID: 2

    demo-app:
        image: demo-app
#       build: https://github.com/OffchainLabs/demo-app.git#alpha
        build: ./demo-app
        ports:
            - "8080:8080"
