version: 2
jobs:
  build:
    docker:
    - image: alpine:3.9
    working_directory: ~/arbitrum
    steps:
    - run:
        name: install system dependencies
        command: |
          apk add boost-dev build-base cmake gcc git go libc-dev libffi-dev linux-headers nodejs npm yarn openssl-dev python3-dev python
          pip3 install codecov coverage
    - checkout
    - run:
        name: build all
        command: |
          yarn
          yarn 'install:all' --ci
    - run:
        name: test arb-avm-cpp
        command: |
          ctest .
          lcov --capture --directory . --output-file coverage.info
          lcov --remove coverage.info --output-file coverage.info '/usr/*' '*/tests/*' '*/external/*'
          lcov --list coverage.info
          codecov -f coverage.info -cF arb-avm-cpp
        working_directory: ~/arbitrum/packages/arb-avm-cpp/debug
    - run:
        name: test arb-avm-go
        command: |
          go test -race -coverprofile=coverage.txt -covermode=atomic ./...
          codecov -cF arb-avm-go
        working_directory: ~/arbitrum/packages/arb-avm-go
    - run:
        name: test arb-bridge-eth
        command: |
          truffle test || true
          codecov -cF arb-bridge-eth
        working_directory: ~/arbitrum/packages/arb-bridge-eth
    - run:
        name: test arb-compiler-evm
        command: |
          coverage run --source=arbitrum/ setup.py test
          cd tests/sol-syscall
          truffle migrate --reset --compile-all --network arbitrum
          coverage run --source=../../arbitrum/ truffle_runner.py compiled.json
          cd ../..
          coverage combine .coverage tests/sol-syscall/.coverage
          codecov -cF arb-compiler-evm
        working_directory: ~/arbitrum/packages/arb-compiler-evm
    - run:
        name: test arb-provider-ethers
        command: |
          yarn jest --coverage
          codecov -cF arb-provider-ethers
        working_directory: ~/arbitrum/packages/arb-provider-ethers
    - run:
        name: test arb-provider-go
        command: |
          go test -race -coverprofile=coverage.txt -covermode=atomic ./...
          codecov -cF arb-provider-go
        working_directory: ~/arbitrum/packages/arb-provider-go
    - run:
        name: test arb-provider-truffle
        command: |
          yarn jest --coverage --pass-with-no-tests
          codecov -cF arb-provider-truffle
        working_directory: ~/arbitrum/packages/arb-provider-truffle
    - run:
        name: test arb-provider-web3
        command: |
          yarn jest --coverage --pass-with-no-tests
          codecov -cF arb-provider-web3
        working_directory: ~/arbitrum/packages/arb-provider-web3
    - run:
        name: test arb-util
        command: |
          go test -race -coverprofile=coverage.txt -covermode=atomic ./...
          codecov -cF arb-util
        working_directory: ~/arbitrum/packages/arb-util
    - run:
        name: test arb-validator
        command: |
          go test -race -coverprofile=coverage.txt -covermode=atomic ./...
          coverage -cF arb-validator
        working_directory: ~/arbitrum/packages/arb-validator
